### ISSUE TITLE
Deploy on fly.io using Docker

### ISSUE THREAD

**Issue by gianpispi** [crbelaus/bun#32]
Something is not clear to me, so I'm gonna ask here.
I'm deploying to fly.io, which automatically creates a Dockerfile. Inside the Dockerfile it runs `RUN mix assets.deploy`.
This causes some issues. I added a rule to also `RUN mix assets.setup`, but it keep failing. Should I also run `bun install` in the assets folder before running deploy?

this is my setup:
``` elixir
"assets.setup": ["bun.install"],
"assets.build": ["bun default", "bun css"],
"assets.deploy": ["bun default --minify", "bun css --minify", "phx.digest"]
```

I get this error:
```
 > [builder 14/18] RUN mix assets.deploy:
1.052 19 | import "phoenix_html"
1.052             ^
1.052 error: Could not resolve: "phoenix_html". Maybe you need to "bun install"?
1.052     at /app/assets/js/app.js:19:8
1.052
1.052 21 | import {Socket} from "phoenix"
1.052                           ^
1.052 error: Could not resolve: "phoenix". Maybe you need to "bun install"?
1.052     at /app/assets/js/app.js:21:22
1.052
1.052 22 | import {LiveSocket} from "phoenix_live_view"
1.052                               ^
1.052 error: Could not resolve: "phoenix_live_view". Maybe you need to "bun install"?
1.052     at /app/assets/js/app.js:22:26
1.052
1.052 23 | import topbar from "topbar"
1.052                         ^
1.052 error: Could not resolve: "topbar". Maybe you need to "bun install"?
1.052     at /app/assets/js/app.js:23:20
1.085 ** (Mix) `mix bun default --minify` exited with 1
------
Error: failed to fetch an image or build from source: error building: failed to solve: process "/bin/sh -c mix assets.deploy" did not complete successfully: exit code: 1
```

---
update: I changed the Dockerfile to include `bun install`, and it works now. Is it the best practice tho?

```
RUN mix assets.setup
RUN cd assets && ../_build/bun install --production && cd ..
RUN mix assets.deploy
```

thank you!

**Comment by crbelaus** [comment]
Hey @gianpispi 

This package just installs the Bun executable pinned to the version of your choice. Calling `bun install` to download any dependencies from `package.json` is the developer responsability, so what you are doing is reasonable and expected.
